name: E2E

on:
  workflow_dispatch:

jobs:
  e2e_tests:
    # Required secrets:
    #
    # ENDPOINT : URL where server is running
    # STORAGE_ACCOUNT_NAME : name of the storage where server is assigned to (without blob.core.windows.net)
    # STORAGE_ACCOUNT_KEY : key used to access storage
    name: E2E tests with cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run E2E tests
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
        run: |
          tag=e2e_tests
          docker build -f tests/e2e/Dockerfile -t $tag .
          docker run \
            -e ENDPOINT \
            -e STORAGE_ACCOUNT_NAME \
            -e STORAGE_ACCOUNT_KEY \
            $tag
