name: Unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  go_tests:
    name: Run go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load openvds image
        uses: "./.github/actions/load_openvds_image"

      - name: Run server tests
        run: |
          DOCKER_BUILDKIT=1 docker build \
            -f Dockerfile \
            --build-arg OPENVDS_IMAGE=${{ env.OPENVDS_IMAGE_TAG }} \
            --target tester \
            .
